### ISSUE TITLE
Disable keybind when a runtime inspector is open

### ISSUE THREAD

**Issue by xiaoxiao921** [harbingerofme/DebugToolkit#127]
Investigate disabling keybind when a runtime inspector is open, like UnityExplorer (we already do something similar with the in game chat https://github.com/harbingerofme/DebugToolkit/pull/120)

**Comment by harbingerofme** [comment]
There has to be a native unity way to see if we're typing in a textbox right

**Comment by SChinchi** [comment]
The RoR2 native event system may be worthwhile here:

```
MPEventSystemManager.eventSystems.Values.Any(x => x & x.currentSelectedGameObject)
```

Whenever a UI element is selected, such as an InputField, it is captured there. This works for the console, chat boxes, and RuntimeInspector that I've tested. However, it means the input field for the console, for example, is actually selected. In order to prevent a keybind to execute when the display is open even if no textbox is selected, I can only think that we need to check for the GameObject being present/active. Similar to how we already do `if (ConsoleWindow.instance)`.

Incidentally, this also captures the setting buttons when the cursor is hovering over them and they are highlighted. But for the console and RuntimeInspector, hovering over something doesn't activate anything. you need to have a textbox selected.
