### ISSUE TITLE
[BUG] Binds dont work in Photomode

### ISSUE THREAD

**Issue by VioletChaolan** [harbingerofme/DebugToolkit#186]
**Describe the bug**
any binds created do not work inside photomode camera.

**Does the bug happen without input**
no

**If input is required, which scenes does it go wrong in**
ingame

**Do you have other mods installed?**
Only Debugtoolkit and Photomode.

**Comment by SChinchi** [comment]
Thanks for this, fixed now.

Time is still frozen in photomode, so if your bind is to spawn an enemy, for example, you won't really see much happening.

Actually, the way the mod handles pausing and unpausing is meant only for singleplayer, because it changes the time scale locally. This will creates issues in multiplayer but `time_scale` can sync everyone again. It also resets the time scale to 1 when exiting the mode, no matter what it was before, but both of these issues have to do with the mod's implementation of things.
